
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Sep 04 10:32:47 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MONKEY = 47;
  public static final int CHAR = 53;
  public static final int CONST = 16;
  public static final int NOTEQUAL = 30;
  public static final int FOLLOW = 43;
  public static final int LPAREN = 6;
  public static final int GREATER = 31;
  public static final int SEMI = 5;
  public static final int CONTINUE = 23;
  public static final int FILTER = 50;
  public static final int LESS = 33;
  public static final int MINUS = 25;
  public static final int GREQ = 32;
  public static final int RPAREN = 7;
  public static final int AND = 35;
  public static final int OR = 36;
  public static final int BOOL = 54;
  public static final int COMMA = 8;
  public static final int CLASS = 14;
  public static final int INC = 37;
  public static final int DIV = 27;
  public static final int PLUS = 12;
  public static final int ASSIGN = 9;
  public static final int IF = 17;
  public static final int DOT = 40;
  public static final int TARABA = 46;
  public static final int FINDANY = 44;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 29;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int NUMBER = 51;
  public static final int MOD = 28;
  public static final int IDENT = 52;
  public static final int BREAK = 13;
  public static final int VOID = 21;
  public static final int COLON = 39;
  public static final int FOREACH = 24;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int SKIP = 49;
  public static final int LSQUARE = 41;
  public static final int READ = 20;
  public static final int RSQUARE = 42;
  public static final int WHILE = 18;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 22;
  public static final int PROG = 2;
  public static final int LEQ = 34;
  public static final int DEC = 38;
  public static final int DOLAR = 48;
  public static final int PRINT = 10;
  public static final int FINDANDREPLACE = 45;
}

